baseURL = "http://destroy.systems/"
languageCode = "en-us"
title = "destroy.systems"
theme = "kiera"
cannonifyurls = true

pygmentsCodeFences = true
pygmentsStyle = "monokai"

paginate = 5

summaryLength = 30
enableEmoji = true

[author]
  github = "destroysystems"
  email = "admin@destroy.systems"

[params]
#  tagline = "Test tagline"

[menu]
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30

[taxonomies]
  author = "authors"
  tag = "tags"
